// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu5Ne1PHzTCBWUYCCbxGraLOYr6b_heSg',
    appId: '1:633205843761:web:209604ba50bf40a8d13210',
    messagingSenderId: '633205843761',
    projectId: 'test-4301e',
    authDomain: 'test-4301e.firebaseapp.com',
    storageBucket: 'test-4301e.appspot.com',
    measurementId: 'G-EY9PX5JPWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAII30ewU3C-rURDP9oKRb5-PIcv9OlqXA',
    appId: '1:633205843761:android:132c6949641b528ed13210',
    messagingSenderId: '633205843761',
    projectId: 'test-4301e',
    storageBucket: 'test-4301e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPfdq7LjsA1Bzpe6UKXe6I1WQm0koqCXU',
    appId: '1:633205843761:ios:0a54331a8169a5b1d13210',
    messagingSenderId: '633205843761',
    projectId: 'test-4301e',
    storageBucket: 'test-4301e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPfdq7LjsA1Bzpe6UKXe6I1WQm0koqCXU',
    appId: '1:633205843761:ios:43cc56a6b9c6f77ad13210',
    messagingSenderId: '633205843761',
    projectId: 'test-4301e',
    storageBucket: 'test-4301e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
